version: "3.5"
services:
    web:
      #build: .
      image: culturagovbr/salic-web:1.7
      container_name: salic-web
      ports:
      - "80:80"
      volumes:
      - .:/var/www/salic
      - ./log/apache2:/var/log/apache2
      - ./public/txt:/var/www/salic/public/txt/
      - ./public/plenaria:/var/www/salic/public/plenaria/
      environment:
      - APPLICATION_ENV=development
      - UPDATE_COMPOSER_DEPENDENCIES="false"
      # xDebug configs for 'development' enviroment
      # - XDEBUG_INSTALL="false"
      # - XDEBUG_REMOTE_ENABLE=on
      # - XDEBUG_REMOTE_AUTOSTART=on
      # - XDEBUG_REMOTE_HANDLER=dbgp
      # - XDEBUG_REMOTE_CONNECT_BACK=1
      # - XDEBUG_PROFILER_ENABLE=1
      # - XDEBUG_PROFILER_OUTPUT_DIR=/tmp/www/html
      # - XDEBUG_REMOTE_PORT=9000
      # - XDEBUGINI_PATH=/usr/local/etc/php/conf.d/xdebug.ini
      # - XDEBUG_DEFAULT_ENABLE=1
      # - XDEBUG_IDEKEY=PHPSTORM

      - DB_ADAPTER=PDO_MSSQL
      - DB_USERNAME=sa
      - DB_PASSWORD=salic@123456
      - DB_NAME=sac
      - DB_HOST=salic-mssql
      - DB_PORT=1433
      - DB_PDOTYPE=dblib
      - RECEITA_URL=http://homolog.cultura.gov.br
      - RECEITA_USER=PREENCHER
      - RECEITA_PASSWORD=PREENCHER
      - EMAIL_DEFAULT=PREENCHER
      - EMAIL_TRANSPORT_HOST=PREENCHER
      - EMAIL_TRANSPORT_TYPE=smtp
      - EMAIL_TRANSPORT_AUTH=login
      - EMAIL_TRANSPORT_USERNAME=PREENCHER
      - EMAIL_TRANSPORT_PASSWORD=PREENCHER
      - MOBILE_SALICMOBILEHASH=PREENCHER
      - MOBILE_ENCRYPTHASH=PREENCHER
      - MOBILE_GCMAPIKEY=PREENCHER
      - MOBILE_GCMURL=PREENCHER
      - SENTRY_URL=
      - AVALIACAO_PROPOSTA_HASH=LDASfrwerwer12312QWErwet!Asfdasgftrt45.!!2a
      - URL_BASE=http://salic.cultura.gov.br
      - DISPLAY_ERRORS=1
      - DISPLAY_STARTUP_ERRORS=1
      - JWT_TOKEN=adsa1w681f681awd651123654f
      - HOST_NFE=http://localhost:8080/notas
      - TEST_LOGIN=12345678900
      - TEST_PASSWORD=123456
      links:
      - "salic-mssql"
      networks:
      - salic-network

    salic-mssql:
      image: culturagovbr/salic-mssql:1.1.0-minimo
      container_name: salic-mssql
      ports:
      - "1433:1433"
      environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=salic@123456
      - RESTAURAR_BACKUP=true
      - MIGRAR_DADOS_COM_PYTHON=false
      networks:
      - salic-network

networks:
  salic-network:
    driver: bridge
    name: salic-network
